# ----------------------------
# dev-stage
# ----------------------------
FROM python:3-alpine AS dev-stage

# Add dev_user
RUN groupadd -r dev_user \
    && useradd --no-log-init -r -g dev_user dev_user \
    && mkdir -p /home/dev_user/app \
    && chown --recursive dev_user:dev_user /home/dev_user \
    && chown --recursive dev_user:dev_user /home/dev_user/app

# Set dev_user as default
ENV HOME /home/dev_user
USER dev_user
WORKDIR $HOME/app

# pip install
COPY ./app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copy source
COPY ./app .

# start
EXPOSE 8080
CMD ["python", "./main.py"]
